variables:
  PROJECT: "con_profile"
  ADDONS_PATH: "/home/gitlab-runner/odoo-11.0e/odoo/addons,./CON"
  ODOO_REPO: "/home/gitlab-runner/odoo-11.0e"
  ODOO_VERSION: "11.0"

stages:
  - cq_check
  - odoo_test
  - cleanup

flake8:
  tags:
    - cq_check
  stage: cq_check
  script:
  - flake8 --config=.flake8 .

tests:
  before_script:
    - virtualenv -p python3 odoo-11
    - source odoo-11/bin/activate
  tags:
    - odoo_test
  stage: odoo_test
  script:
  - dropdb --if-exists $CI_BUILD_REF
  - cd $ODOO_REPO
  - cd -
  - createdb --encoding=UTF8 --locale=en_US.UTF-8 --template=template0 -D ramdisk $CI_BUILD_REF
  - cd ..
  - $ODOO_REPO/odoo-bin -d $CI_BUILD_REF --addons-path=$ADDONS_PATH -i $PROJECT --log-level=warn --stop-after-init
  - coverage run $ODOO_REPO/odoo-bin -d $CI_BUILD_REF --addons-path=$ADDONS_PATH -i $PROJECT --test-enable --log-level=warn --stop-after-init
  - coverage html
  - coverage report -i
  - grep pc_cov htmlcov/index.html | egrep -o "[0-9]+\%" | awk '{ print "covered " $1;}'
  - dropdb --if-exists $CI_BUILD_REF

cleanup_job:
  tags:
    - odoo_test
  stage: cleanup
  script:
  - dropdb --if-exists $CI_BUILD_REF
  when: on_failure